"""Creating message table

Revision ID: 470e3fe2a339
Revises: 8cc07bbfb7e7
Create Date: 2022-06-19 17:09:51.196101

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision = '470e3fe2a339'
down_revision = '8cc07bbfb7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_chat_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('edited', sa.Boolean(), server_default=expression.false(), nullable=False),
    sa.Column('read', sa.Boolean(), server_default=expression.false(), nullable=False),
    sa.ForeignKeyConstraint(['user_chat_id'], ['users_chats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
